import AbstractView from "./AbstractView.js";

import linkedin from "../assets/img/linkedin.png";
import github from "../assets/img/github.png";
import whale from "../assets/img/whale.png";

export default class extends AbstractView {
    constructor(params) {
        super(params);
        this.setTitle("Contact");
    }

    async getHtml() {
        return `
            <div id="contact">

                <div class="social-medias">
                    <a target="_blank" class="social-medias__icons" href="https://www.linkedin.com/in/anne-bequet/">
                        <img src=${linkedin} alt="linkedin"/>
                    </a>
                    <a target="_blank" class="social-medias__icons" href="https://github.com/annebequet">
                        <img src=${github} alt="github"/>
                    </a>
                </div>

                <div id="contact__header">
                    <h1>I would love to hear from you,</h1>
                    <h1>Feel free to drop me a line.</h1>
                    <a class="nav__link" id="my-email" HREF="mailto:a.bequet@live.fr">a.bequet@live.fr</a>
                </div>

                <div id="whale-contact">
                    <img src=${whale} alt="whale" id="whale-contact__picture"/>

                    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

                    <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M-1.98,-0.50 C150.39,223.20 349.20,-50.04 500.00,50.03 L500.00,150.13 L-0.00,150.13 Z" style="stroke: none; fill: #08f;"></path></svg>
                </div>

                <div id="aknowledgments">
                    <p id="credits">Credits :</p>
                    <a class="nav__link credit-list" href='https://pngtree.com/so/illustration'>Acrylic whale : pngtree.com</a></p>
                    <p class="credit-list">Humpback whale : John3 on TopPng</p>
                </div>
            </div>
        `;
    }
}